name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Validate Maven
        run: |
          if [ -f mvnw ]; then
            chmod +x mvnw
            ./mvnw -v
          else
            mvn -v
          fi

      - name: Build (no tests)
        run: |
          if [ -f mvnw ]; then
            ./mvnw -B -ntp -DskipTests compile
          else
            mvn -B -ntp -DskipTests compile
          fi

      - name: Run unit & integration tests (Surefire + Failsafe)
        run: |
          if [ -f mvnw ]; then
            ./mvnw -B -ntp verify
          else
            mvn -B -ntp verify
          fi

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maven-test-reports
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
            **/target/site/**
