# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    strategy:
      matrix:
        java: [ '21' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Validate Maven wrapper
        run: |
          if [ -f mvnw ]; then
            chmod +x mvnw
            ./mvnw -v
          else
            mvn -v
          fi

      - name: Build without tests
        run: |
          if [ -f mvnw ]; then
            ./mvnw -B -ntp -DskipTests clean compile
          else
            mvn -B -ntp -DskipTests clean compile
          fi

      - name: Run unit tests (Surefire)
        run: |
          if [ -f mvnw ]; then
            ./mvnw -B -ntp test || echo "Unit tests failed or not found"
          else
            mvn -B -ntp test || echo "Unit tests failed or not found"
          fi

      - name: Run integration tests (Failsafe) with Docker DB
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
          SPRING_DATASOURCE_USERNAME: test
          SPRING_DATASOURCE_PASSWORD: test
          SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
        run: |
          if [ -f mvnw ]; then
            ./mvnw -B -ntp verify -DskipUnitTests || echo "Integration tests failed or not found"
          else
            mvn -B -ntp verify -DskipUnitTests || echo "Integration tests failed or not found"
          fi

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports-java${{ matrix.java }}
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**
            **/target/site/**

      - name: Build Docker image
        run: |
          docker build -t lab2-back:test .

      - name: Test Docker Compose (smoke test)
        run: |
          cp docker-compose.yaml docker-compose-ci.yaml
          sed -i 's/db:/postgres:/g' docker-compose-ci.yaml
          docker compose -f docker-compose-ci.yaml up --build -d app
          sleep 10
          curl -f http://localhost:8080/actuator/health || exit 1
        env:
          DB_NAME: testdb
          DB_USER: test
          DB_PASSWORD: test