name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build JAR
        run: |
          if [ -f mvnw ]; then
            ./mvnw -B -ntp clean package -DskipTests
          else
            mvn -B -ntp clean package -DskipTests
          fi

      - name: Build Docker image
        run: docker build -t lab2-back:test .

      - name: Run container (smoke test)
        run: |
          docker run -d --name app-test \
            -p 8080:8080 \
            lab2-back:test

          echo "Waiting for container to start..."
          sleep 15

          echo "Container is running:"
          docker ps | grep app-test

          echo "Logs:"
          docker logs app-test

      - name: Cleanup
        if: always()
        run: |
          docker stop app-test || true
          docker rm app-test || true